### ISSUE TITLE
Sample code to generate hpatch descriptors not working.

### ISSUE THREAD

**Issue by trueutkarsh** [DagnyT/hardnet#1]
Hey @DagnyT 
This issue is regarding the last few changes in the repo where you added the *extract_hardnet_desc_from_hpatches_file.py* .
The script is not working as it is suppose to be and I have few doubts regarding it

* The paper suggests two step normalization one global and one locally for a patch itself
https://github.com/DagnyT/hardnet/blob/1f033f3f1278bb00e2943dc50ff50c1fba787975/examples/extract_hardnet_desc_from_hpatches_file.py#L105-L106
How do you justify this ? should'nt it be
`patches = (patches - patches.mean())/patches.std()`

*Next issue is an important one because of which the script fails to run
https://github.com/DagnyT/hardnet/blob/1f033f3f1278bb00e2943dc50ff50c1fba787975/examples/extract_hardnet_desc_from_hpatches_file.py#L71-L72
https://github.com/DagnyT/hardnet/blob/1f033f3f1278bb00e2943dc50ff50c1fba787975/examples/extract_hardnet_desc_from_hpatches_file.py#L22-L23

The way the code expands the mean tensor(1) or std tensor (2) is incorrect, because of which the error

```
(utkarsh) utkarsh@Viper:~/project/codeBase/hardnet/examples$ python extract_hardnet_desc_from_hpatches_file.py imgs/ref.png out.txt
(72995, 65)
Traceback (most recent call last):
  File "extract_hardnet_desc_from_hpatches_file.py", line 125, in <module>
    out_a = model(data_a)
  File "/home/utkarsh/anaconda3/envs/utkarsh/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "extract_hardnet_desc_from_hpatches_file.py", line 72, in forward
    (input - mp.unsqueeze(-1).unsqueeze(-1).expand_as(input)) / sp.unsqueeze(-1).unsqueeze(1).expand_as(input))
  File "/home/utkarsh/anaconda3/envs/utkarsh/lib/python2.7/site-packages/torch/autograd/variable.py", line 725, in expand_as
    return Expand.apply(self, (tensor.size(),))
  File "/home/utkarsh/anaconda3/envs/utkarsh/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 111, in forward
    result = i.expand(*new_size)
RuntimeError: The expanded size of the tensor (1) must match the existing size (128) at non-singleton dimension 1. at /opt/conda/conda-bld/pytorch_1502006348621/work/torch/lib/THC/generic/THCTensor.c:323
```
I had resolved this by adding an extra ```.unsqueeze(-1)``` in the above mentioned lines.

What are your thoughts over this ?

**Comment by ducha-aiki** [comment]
Hi @trueutkarsh 
Thanks for catch. Error was because pytorch update https://github.com/pytorch/pytorch/pull/1563 changed output shape of the mean function. We have fixed it before in main code, but forget about example. Now it works.

Regarding 

> How do you justify this ? should'nt it be
patches = (patches - patches.mean())/patches.std()

No, code is correct. Global normalization is done by training set statistics and is hardcoded for Liberty dataset. 

Local normalization is done per patch inside the network.
