### ISSUE TITLE
The test code of the caffe model is wrong

### ISSUE THREAD

**Issue by hurricane2018** [DagnyT/hardnet#11]
When I use the test provide example:

cd examples/caffe
python extract_hardnetCaffe_desc_from_hpatches_file.py ../imgs/ref.png hardnet_caffe.txt

1123 patches to describe in ../imgs/ref.png
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 27:3: Invalid value for boolean field "bias_term". Value: "False".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0424 00:21:30.764016 12746 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: HardNet.prototxt
*** Check failure stack trace: **

Something is wrong with HardNet.prototxt or HardNet++.caffemodel . I guess the error comes from the caffemodel. Hope you can modify it !

**Comment by hurricane2018** [comment]
I also test your previous version, the result is ok. But the latest caffe model has error

**Comment by ducha-aiki** [comment]
Thanks! We will check, which is outdated - prototxt or weights and update them soon.

**Comment by ducha-aiki** [comment]
> old-ufo@oldufo-UX303UB:~/dev$ git clone https://github.com/DagnyT/hardnet test_hardnet
> 
> Cloning into 'test_hardnet'...
> remote: Counting objects: 457, done.
> remote: Compressing objects: 100% (39/39), done.
> remote: Total 457 (delta 36), reused 42 (delta 24), pack-reused 394
> Receiving objects: 100% (457/457), 102.39 MiB | 1.21 MiB/s, done.
> Resolving deltas: 100% (228/228), done.
> Checking connectivity... done.
> old-ufo@oldufo-UX303UB:~/dev$ cd test_hardnet

> old-ufo@oldufo-UX303UB:~/dev/test_hardnet$ cd examples/caffe/

> old-ufo@oldufo-UX303UB:~/dev/test_hardnet/examples/caffe$ python 
extract_hardnetCaffe_desc_from_hpatches_file.py ../imgs/ref.png hardnet_caffe.txt
> 1123 patches to describe in ../imgs/ref.png
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0502 15:37:06.436084 29145 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: HardNet.prototxt
> I0502 15:37:06.436121 29145 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
> I0502 15:37:06.436303 29145 net.cpp:51] Initializing net from parameters: 
> name: "HardNet"
> state {
>   phase: TEST
>   level: 0
> }
> layer {
>   name: "data"
>   type: "Input"
>   top: "data"
>   input_param {
>     shape {
>       dim: 256
>       dim: 1
>       dim: 32
>       dim: 32
>     }
>   }
> }
> layer {
>   name: "data_norm"
>   type: "MVN"
>   bottom: "data"
>   top: "data_norm"
> }
> layer {
>   name: "conv1"
>   type: "Convolution"
>   bottom: "data_norm"
>   top: "conv1"
>   convolution_param {
>     num_output: 32
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 1
>   }
> }
> layer {
>   name: "conv1_BN"
>   type: "BatchNorm"
>   bottom: "conv1"
>   top: "conv1_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "relu1"
>   type: "ReLU"
>   bottom: "conv1_BN"
>   top: "relu1"
> }
> layer {
>   name: "conv2"
>   type: "Convolution"
>   bottom: "relu1"
>   top: "conv2"
>   convolution_param {
>     num_output: 32
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 1
>   }
> }
> layer {
>   name: "conv2_BN"
>   type: "BatchNorm"
>   bottom: "conv2"
>   top: "conv2_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "relu2"
>   type: "ReLU"
>   bottom: "conv2_BN"
>   top: "relu2"
> }
> layer {
>   name: "conv3"
>   type: "Convolution"
>   bottom: "relu2"
>   top: "conv3"
>   convolution_param {
>     num_output: 64
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 2
>   }
> }
> layer {
>   name: "conv3_BN"
>   type: "BatchNorm"
>   bottom: "conv3"
>   top: "conv3_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "relu3"
>   type: "ReLU"
>   bottom: "conv3_BN"
>   top: "relu3"
> }
> layer {
>   name: "conv4"
>   type: "Convolution"
>   bottom: "relu3"
>   top: "conv4"
>   convolution_param {
>     num_output: 64
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 1
>   }
> }
> layer {
>   name: "conv4_BN"
>   type: "BatchNorm"
>   bottom: "conv4"
>   top: "conv4_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "relu4"
>   type: "ReLU"
>   bottom: "conv4_BN"
>   top: "relu4"
> }
> layer {
>   name: "conv5"
>   type: "Convolution"
>   bottom: "relu4"
>   top: "conv5"
>   convolution_param {
>     num_output: 128
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 2
>   }
> }
> layer {
>   name: "conv5_BN"
>   type: "BatchNorm"
>   bottom: "conv5"
>   top: "conv5_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "relu5"
>   type: "ReLU"
>   bottom: "conv5_BN"
>   top: "relu5"
> }
> layer {
>   name: "conv6"
>   type: "Convolution"
>   bottom: "relu5"
>   top: "conv6"
>   convolution_param {
>     num_output: 128
>     bias_term: false
>     pad: 1
>     kernel_size: 3
>     stride: 1
>   }
> }
> layer {
>   name: "conv6_BN"
>   type: "BatchNorm"
>   bottom: "conv6"
>   top: "conv6_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "relu6"
>   type: "ReLU"
>   bottom: "conv6_BN"
>   top: "relu6"
> }
> layer {
>   name: "conv7"
>   type: "Convolution"
>   bottom: "relu6"
>   top: "conv7"
>   convolution_param {
>     num_output: 128
>     bias_term: false
>     kernel_size: 8
>   }
> }
> layer {
>   name: "conv7_BN"
>   type: "BatchNorm"
>   bottom: "conv7"
>   top: "conv7_BN"
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   param {
>     lr_mult: 0
>     decay_mult: 0
>   }
>   batch_norm_param {
>     use_global_stats: true
>     moving_average_fraction: 1
>     eps: 1e-05
>   }
> }
> layer {
>   name: "conv7red"
>   type: "Reduction"
>   bottom: "conv7_BN"
>   top: "conv7red"
>   reduction_param {
>     operation: SUMSQ
>     axis: 1
>   }
> }
> layer {
>   name: "conv7sqrt"
>   type: "Power"
>   bottom: "conv7red"
>   top: "conv7sqrt"
>   power_param {
>     power: -0.5
>   }
> }
> layer {
>   name: "den_reshape"
>   type: "Reshape"
>   bottom: "conv7sqrt"
>   top: "den_reshape"
>   reshape_param {
>     shape {
>       dim: 1
>     }
>     axis: -1
>     num_axes: 0
>   }
> }
> layer {
>   name: "den_tiled"
>   type: "Tile"
>   bottom: "den_reshape"
>   top: "den_tiled"
>   tile_param {
>     axis: 1
>     tiles: 128
>   }
> }
> layer {
>   name: "conv7_flat"
>   type: "Flatten"
>   bottom: "conv7_BN"
>   top: "conv7_flat"
> }
> layer {
>   name: "final"
>   type: "Eltwise"
>   bottom: "conv7_flat"
>   bottom: "den_tiled"
>   top: "final"
>   eltwise_param {
>     operation: PROD
>   }
> }
> I0502 15:37:06.436517 29145 layer_factory.hpp:77] Creating layer data
> I0502 15:37:06.436528 29145 net.cpp:84] Creating Layer data
> I0502 15:37:06.436535 29145 net.cpp:380] data -> data
> I0502 15:37:06.446427 29145 net.cpp:122] Setting up data
> I0502 15:37:06.446463 29145 net.cpp:129] Top shape: 256 1 32 32 (262144)
> I0502 15:37:06.446468 29145 net.cpp:137] Memory required for data: 1048576
> I0502 15:37:06.446477 29145 layer_factory.hpp:77] Creating layer data_norm
> I0502 15:37:06.446491 29145 net.cpp:84] Creating Layer data_norm
> I0502 15:37:06.446496 29145 net.cpp:406] data_norm <- data
> I0502 15:37:06.446507 29145 net.cpp:380] data_norm -> data_norm
> I0502 15:37:06.447132 29145 net.cpp:122] Setting up data_norm
> I0502 15:37:06.447146 29145 net.cpp:129] Top shape: 256 1 32 32 (262144)
> I0502 15:37:06.447152 29145 net.cpp:137] Memory required for data: 2097152
> I0502 15:37:06.447158 29145 layer_factory.hpp:77] Creating layer conv1
> I0502 15:37:06.447172 29145 net.cpp:84] Creating Layer conv1
> I0502 15:37:06.447178 29145 net.cpp:406] conv1 <- data_norm
> I0502 15:37:06.447186 29145 net.cpp:380] conv1 -> conv1
> I0502 15:37:06.998322 29145 net.cpp:122] Setting up conv1
> I0502 15:37:06.998348 29145 net.cpp:129] Top shape: 256 32 32 32 (8388608)
> I0502 15:37:06.998351 29145 net.cpp:137] Memory required for data: 35651584
> I0502 15:37:06.998363 29145 layer_factory.hpp:77] Creating layer conv1_BN
> I0502 15:37:06.998373 29145 net.cpp:84] Creating Layer conv1_BN
> I0502 15:37:06.998378 29145 net.cpp:406] conv1_BN <- conv1
> I0502 15:37:06.998383 29145 net.cpp:380] conv1_BN -> conv1_BN
> I0502 15:37:06.998586 29145 net.cpp:122] Setting up conv1_BN
> I0502 15:37:06.998592 29145 net.cpp:129] Top shape: 256 32 32 32 (8388608)
> I0502 15:37:06.998595 29145 net.cpp:137] Memory required for data: 69206016
> I0502 15:37:06.998603 29145 layer_factory.hpp:77] Creating layer relu1
> I0502 15:37:06.998610 29145 net.cpp:84] Creating Layer relu1
> I0502 15:37:06.998613 29145 net.cpp:406] relu1 <- conv1_BN
> I0502 15:37:06.998616 29145 net.cpp:380] relu1 -> relu1
> I0502 15:37:06.999054 29145 net.cpp:122] Setting up relu1
> I0502 15:37:06.999064 29145 net.cpp:129] Top shape: 256 32 32 32 (8388608)
> I0502 15:37:06.999068 29145 net.cpp:137] Memory required for data: 102760448
> I0502 15:37:06.999070 29145 layer_factory.hpp:77] Creating layer conv2
> I0502 15:37:06.999078 29145 net.cpp:84] Creating Layer conv2
> I0502 15:37:06.999081 29145 net.cpp:406] conv2 <- relu1
> I0502 15:37:06.999085 29145 net.cpp:380] conv2 -> conv2
> I0502 15:37:07.000720 29145 net.cpp:122] Setting up conv2
> I0502 15:37:07.000732 29145 net.cpp:129] Top shape: 256 32 32 32 (8388608)
> I0502 15:37:07.000735 29145 net.cpp:137] Memory required for data: 136314880
> I0502 15:37:07.000742 29145 layer_factory.hpp:77] Creating layer conv2_BN
> I0502 15:37:07.000748 29145 net.cpp:84] Creating Layer conv2_BN
> I0502 15:37:07.000752 29145 net.cpp:406] conv2_BN <- conv2
> I0502 15:37:07.000756 29145 net.cpp:380] conv2_BN -> conv2_BN
> I0502 15:37:07.000941 29145 net.cpp:122] Setting up conv2_BN
> I0502 15:37:07.000946 29145 net.cpp:129] Top shape: 256 32 32 32 (8388608)
> I0502 15:37:07.000949 29145 net.cpp:137] Memory required for data: 169869312
> I0502 15:37:07.000957 29145 layer_factory.hpp:77] Creating layer relu2
> I0502 15:37:07.000960 29145 net.cpp:84] Creating Layer relu2
> I0502 15:37:07.000963 29145 net.cpp:406] relu2 <- conv2_BN
> I0502 15:37:07.000967 29145 net.cpp:380] relu2 -> relu2
> I0502 15:37:07.001166 29145 net.cpp:122] Setting up relu2
> I0502 15:37:07.001173 29145 net.cpp:129] Top shape: 256 32 32 32 (8388608)
> I0502 15:37:07.001176 29145 net.cpp:137] Memory required for data: 203423744
> I0502 15:37:07.001179 29145 layer_factory.hpp:77] Creating layer conv3
> I0502 15:37:07.001186 29145 net.cpp:84] Creating Layer conv3
> I0502 15:37:07.001189 29145 net.cpp:406] conv3 <- relu2
> I0502 15:37:07.001194 29145 net.cpp:380] conv3 -> conv3
> I0502 15:37:07.002969 29145 net.cpp:122] Setting up conv3
> I0502 15:37:07.002979 29145 net.cpp:129] Top shape: 256 64 16 16 (4194304)
> I0502 15:37:07.002982 29145 net.cpp:137] Memory required for data: 220200960
> I0502 15:37:07.002990 29145 layer_factory.hpp:77] Creating layer conv3_BN
> I0502 15:37:07.002995 29145 net.cpp:84] Creating Layer conv3_BN
> I0502 15:37:07.002998 29145 net.cpp:406] conv3_BN <- conv3
> I0502 15:37:07.003003 29145 net.cpp:380] conv3_BN -> conv3_BN
> I0502 15:37:07.003170 29145 net.cpp:122] Setting up conv3_BN
> I0502 15:37:07.003176 29145 net.cpp:129] Top shape: 256 64 16 16 (4194304)
> I0502 15:37:07.003180 29145 net.cpp:137] Memory required for data: 236978176
> I0502 15:37:07.003185 29145 layer_factory.hpp:77] Creating layer relu3
> I0502 15:37:07.003190 29145 net.cpp:84] Creating Layer relu3
> I0502 15:37:07.003192 29145 net.cpp:406] relu3 <- conv3_BN
> I0502 15:37:07.003196 29145 net.cpp:380] relu3 -> relu3
> I0502 15:37:07.003625 29145 net.cpp:122] Setting up relu3
> I0502 15:37:07.003634 29145 net.cpp:129] Top shape: 256 64 16 16 (4194304)
> I0502 15:37:07.003638 29145 net.cpp:137] Memory required for data: 253755392
> I0502 15:37:07.003640 29145 layer_factory.hpp:77] Creating layer conv4
> I0502 15:37:07.003646 29145 net.cpp:84] Creating Layer conv4
> I0502 15:37:07.003649 29145 net.cpp:406] conv4 <- relu3
> I0502 15:37:07.003654 29145 net.cpp:380] conv4 -> conv4
> I0502 15:37:07.005108 29145 net.cpp:122] Setting up conv4
> I0502 15:37:07.005118 29145 net.cpp:129] Top shape: 256 64 16 16 (4194304)
> I0502 15:37:07.005121 29145 net.cpp:137] Memory required for data: 270532608
> I0502 15:37:07.005126 29145 layer_factory.hpp:77] Creating layer conv4_BN
> I0502 15:37:07.005131 29145 net.cpp:84] Creating Layer conv4_BN
> I0502 15:37:07.005134 29145 net.cpp:406] conv4_BN <- conv4
> I0502 15:37:07.005139 29145 net.cpp:380] conv4_BN -> conv4_BN
> I0502 15:37:07.005314 29145 net.cpp:122] Setting up conv4_BN
> I0502 15:37:07.005321 29145 net.cpp:129] Top shape: 256 64 16 16 (4194304)
> I0502 15:37:07.005323 29145 net.cpp:137] Memory required for data: 287309824
> I0502 15:37:07.005329 29145 layer_factory.hpp:77] Creating layer relu4
> I0502 15:37:07.005333 29145 net.cpp:84] Creating Layer relu4
> I0502 15:37:07.005336 29145 net.cpp:406] relu4 <- conv4_BN
> I0502 15:37:07.005339 29145 net.cpp:380] relu4 -> relu4
> I0502 15:37:07.005539 29145 net.cpp:122] Setting up relu4
> I0502 15:37:07.005548 29145 net.cpp:129] Top shape: 256 64 16 16 (4194304)
> I0502 15:37:07.005550 29145 net.cpp:137] Memory required for data: 304087040
> I0502 15:37:07.005553 29145 layer_factory.hpp:77] Creating layer conv5
> I0502 15:37:07.005558 29145 net.cpp:84] Creating Layer conv5
> I0502 15:37:07.005561 29145 net.cpp:406] conv5 <- relu4
> I0502 15:37:07.005566 29145 net.cpp:380] conv5 -> conv5
> I0502 15:37:07.007211 29145 net.cpp:122] Setting up conv5
> I0502 15:37:07.007222 29145 net.cpp:129] Top shape: 256 128 8 8 (2097152)
> I0502 15:37:07.007225 29145 net.cpp:137] Memory required for data: 312475648
> I0502 15:37:07.007238 29145 layer_factory.hpp:77] Creating layer conv5_BN
> I0502 15:37:07.007247 29145 net.cpp:84] Creating Layer conv5_BN
> I0502 15:37:07.007251 29145 net.cpp:406] conv5_BN <- conv5
> I0502 15:37:07.007257 29145 net.cpp:380] conv5_BN -> conv5_BN
> I0502 15:37:07.007437 29145 net.cpp:122] Setting up conv5_BN
> I0502 15:37:07.007444 29145 net.cpp:129] Top shape: 256 128 8 8 (2097152)
> I0502 15:37:07.007447 29145 net.cpp:137] Memory required for data: 320864256
> I0502 15:37:07.007452 29145 layer_factory.hpp:77] Creating layer relu5
> I0502 15:37:07.007460 29145 net.cpp:84] Creating Layer relu5
> I0502 15:37:07.007463 29145 net.cpp:406] relu5 <- conv5_BN
> I0502 15:37:07.007467 29145 net.cpp:380] relu5 -> relu5
> I0502 15:37:07.007917 29145 net.cpp:122] Setting up relu5
> I0502 15:37:07.007926 29145 net.cpp:129] Top shape: 256 128 8 8 (2097152)
> I0502 15:37:07.007930 29145 net.cpp:137] Memory required for data: 329252864
> I0502 15:37:07.007932 29145 layer_factory.hpp:77] Creating layer conv6
> I0502 15:37:07.007939 29145 net.cpp:84] Creating Layer conv6
> I0502 15:37:07.007942 29145 net.cpp:406] conv6 <- relu5
> I0502 15:37:07.007946 29145 net.cpp:380] conv6 -> conv6
> I0502 15:37:07.009490 29145 net.cpp:122] Setting up conv6
> I0502 15:37:07.009501 29145 net.cpp:129] Top shape: 256 128 8 8 (2097152)
> I0502 15:37:07.009505 29145 net.cpp:137] Memory required for data: 337641472
> I0502 15:37:07.009511 29145 layer_factory.hpp:77] Creating layer conv6_BN
> I0502 15:37:07.009518 29145 net.cpp:84] Creating Layer conv6_BN
> I0502 15:37:07.009522 29145 net.cpp:406] conv6_BN <- conv6
> I0502 15:37:07.009528 29145 net.cpp:380] conv6_BN -> conv6_BN
> I0502 15:37:07.009717 29145 net.cpp:122] Setting up conv6_BN
> I0502 15:37:07.009723 29145 net.cpp:129] Top shape: 256 128 8 8 (2097152)
> I0502 15:37:07.009727 29145 net.cpp:137] Memory required for data: 346030080
> I0502 15:37:07.009732 29145 layer_factory.hpp:77] Creating layer relu6
> I0502 15:37:07.009738 29145 net.cpp:84] Creating Layer relu6
> I0502 15:37:07.009742 29145 net.cpp:406] relu6 <- conv6_BN
> I0502 15:37:07.009747 29145 net.cpp:380] relu6 -> relu6
> I0502 15:37:07.010200 29145 net.cpp:122] Setting up relu6
> I0502 15:37:07.010210 29145 net.cpp:129] Top shape: 256 128 8 8 (2097152)
> I0502 15:37:07.010215 29145 net.cpp:137] Memory required for data: 354418688
> I0502 15:37:07.010218 29145 layer_factory.hpp:77] Creating layer conv7
> I0502 15:37:07.010226 29145 net.cpp:84] Creating Layer conv7
> I0502 15:37:07.010228 29145 net.cpp:406] conv7 <- relu6
> I0502 15:37:07.010236 29145 net.cpp:380] conv7 -> conv7
> I0502 15:37:07.013535 29145 net.cpp:122] Setting up conv7
> I0502 15:37:07.013562 29145 net.cpp:129] Top shape: 256 128 1 1 (32768)
> I0502 15:37:07.013566 29145 net.cpp:137] Memory required for data: 354549760
> I0502 15:37:07.013573 29145 layer_factory.hpp:77] Creating layer conv7_BN
> I0502 15:37:07.013592 29145 net.cpp:84] Creating Layer conv7_BN
> I0502 15:37:07.013597 29145 net.cpp:406] conv7_BN <- conv7
> I0502 15:37:07.013605 29145 net.cpp:380] conv7_BN -> conv7_BN
> I0502 15:37:07.013824 29145 net.cpp:122] Setting up conv7_BN
> I0502 15:37:07.013834 29145 net.cpp:129] Top shape: 256 128 1 1 (32768)
> I0502 15:37:07.013836 29145 net.cpp:137] Memory required for data: 354680832
> I0502 15:37:07.013844 29145 layer_factory.hpp:77] Creating layer conv7_BN_conv7_BN_0_split
> I0502 15:37:07.013849 29145 net.cpp:84] Creating Layer conv7_BN_conv7_BN_0_split
> I0502 15:37:07.013852 29145 net.cpp:406] conv7_BN_conv7_BN_0_split <- conv7_BN
> I0502 15:37:07.013859 29145 net.cpp:380] conv7_BN_conv7_BN_0_split -> conv7_BN_conv7_BN_0_split_0
> I0502 15:37:07.013866 29145 net.cpp:380] conv7_BN_conv7_BN_0_split -> conv7_BN_conv7_BN_0_split_1
> I0502 15:37:07.013914 29145 net.cpp:122] Setting up conv7_BN_conv7_BN_0_split
> I0502 15:37:07.013919 29145 net.cpp:129] Top shape: 256 128 1 1 (32768)
> I0502 15:37:07.013923 29145 net.cpp:129] Top shape: 256 128 1 1 (32768)
> I0502 15:37:07.013926 29145 net.cpp:137] Memory required for data: 354942976
> I0502 15:37:07.013928 29145 layer_factory.hpp:77] Creating layer conv7red
> I0502 15:37:07.013936 29145 net.cpp:84] Creating Layer conv7red
> I0502 15:37:07.013938 29145 net.cpp:406] conv7red <- conv7_BN_conv7_BN_0_split_0
> I0502 15:37:07.013945 29145 net.cpp:380] conv7red -> conv7red
> I0502 15:37:07.013972 29145 net.cpp:122] Setting up conv7red
> I0502 15:37:07.013975 29145 net.cpp:129] Top shape: 256 (256)
> I0502 15:37:07.013978 29145 net.cpp:137] Memory required for data: 354944000
> I0502 15:37:07.013981 29145 layer_factory.hpp:77] Creating layer conv7sqrt
> I0502 15:37:07.013988 29145 net.cpp:84] Creating Layer conv7sqrt
> I0502 15:37:07.013989 29145 net.cpp:406] conv7sqrt <- conv7red
> I0502 15:37:07.013994 29145 net.cpp:380] conv7sqrt -> conv7sqrt
> I0502 15:37:07.014014 29145 net.cpp:122] Setting up conv7sqrt
> I0502 15:37:07.014019 29145 net.cpp:129] Top shape: 256 (256)
> I0502 15:37:07.014022 29145 net.cpp:137] Memory required for data: 354945024
> I0502 15:37:07.014026 29145 layer_factory.hpp:77] Creating layer den_reshape
> I0502 15:37:07.014032 29145 net.cpp:84] Creating Layer den_reshape
> I0502 15:37:07.014036 29145 net.cpp:406] den_reshape <- conv7sqrt
> I0502 15:37:07.014042 29145 net.cpp:380] den_reshape -> den_reshape
> I0502 15:37:07.014086 29145 net.cpp:122] Setting up den_reshape
> I0502 15:37:07.014091 29145 net.cpp:129] Top shape: 256 1 (256)
> I0502 15:37:07.014093 29145 net.cpp:137] Memory required for data: 354946048
> I0502 15:37:07.014097 29145 layer_factory.hpp:77] Creating layer den_tiled
> I0502 15:37:07.014103 29145 net.cpp:84] Creating Layer den_tiled
> I0502 15:37:07.014107 29145 net.cpp:406] den_tiled <- den_reshape
> I0502 15:37:07.014112 29145 net.cpp:380] den_tiled -> den_tiled
> I0502 15:37:07.014149 29145 net.cpp:122] Setting up den_tiled
> I0502 15:37:07.014155 29145 net.cpp:129] Top shape: 256 128 (32768)
> I0502 15:37:07.014158 29145 net.cpp:137] Memory required for data: 355077120
> I0502 15:37:07.014161 29145 layer_factory.hpp:77] Creating layer conv7_flat
> I0502 15:37:07.014168 29145 net.cpp:84] Creating Layer conv7_flat
> I0502 15:37:07.014174 29145 net.cpp:406] conv7_flat <- conv7_BN_conv7_BN_0_split_1
> I0502 15:37:07.014179 29145 net.cpp:380] conv7_flat -> conv7_flat
> I0502 15:37:07.014206 29145 net.cpp:122] Setting up conv7_flat
> I0502 15:37:07.014211 29145 net.cpp:129] Top shape: 256 128 (32768)
> I0502 15:37:07.014215 29145 net.cpp:137] Memory required for data: 355208192
> I0502 15:37:07.014219 29145 layer_factory.hpp:77] Creating layer final
> I0502 15:37:07.014225 29145 net.cpp:84] Creating Layer final
> I0502 15:37:07.014228 29145 net.cpp:406] final <- conv7_flat
> I0502 15:37:07.014232 29145 net.cpp:406] final <- den_tiled
> I0502 15:37:07.014240 29145 net.cpp:380] final -> final
> I0502 15:37:07.014262 29145 net.cpp:122] Setting up final
> I0502 15:37:07.014267 29145 net.cpp:129] Top shape: 256 128 (32768)
> I0502 15:37:07.014271 29145 net.cpp:137] Memory required for data: 355339264
> I0502 15:37:07.014274 29145 net.cpp:200] final does not need backward computation.
> I0502 15:37:07.014279 29145 net.cpp:200] conv7_flat does not need backward computation.
> I0502 15:37:07.014286 29145 net.cpp:200] den_tiled does not need backward computation.
> I0502 15:37:07.014293 29145 net.cpp:200] den_reshape does not need backward computation.
> I0502 15:37:07.014297 29145 net.cpp:200] conv7sqrt does not need backward computation.
> I0502 15:37:07.014300 29145 net.cpp:200] conv7red does not need backward computation.
> I0502 15:37:07.014305 29145 net.cpp:200] conv7_BN_conv7_BN_0_split does not need backward computation.
> I0502 15:37:07.014309 29145 net.cpp:200] conv7_BN does not need backward computation.
> I0502 15:37:07.014314 29145 net.cpp:200] conv7 does not need backward computation.
> I0502 15:37:07.014318 29145 net.cpp:200] relu6 does not need backward computation.
> I0502 15:37:07.014322 29145 net.cpp:200] conv6_BN does not need backward computation.
> I0502 15:37:07.014327 29145 net.cpp:200] conv6 does not need backward computation.
> I0502 15:37:07.014330 29145 net.cpp:200] relu5 does not need backward computation.
> I0502 15:37:07.014334 29145 net.cpp:200] conv5_BN does not need backward computation.
> I0502 15:37:07.014346 29145 net.cpp:200] conv5 does not need backward computation.
> I0502 15:37:07.014351 29145 net.cpp:200] relu4 does not need backward computation.
> I0502 15:37:07.014355 29145 net.cpp:200] conv4_BN does not need backward computation.
> I0502 15:37:07.014359 29145 net.cpp:200] conv4 does not need backward computation.
> I0502 15:37:07.014364 29145 net.cpp:200] relu3 does not need backward computation.
> I0502 15:37:07.014369 29145 net.cpp:200] conv3_BN does not need backward computation.
> I0502 15:37:07.014372 29145 net.cpp:200] conv3 does not need backward computation.
> I0502 15:37:07.014376 29145 net.cpp:200] relu2 does not need backward computation.
> I0502 15:37:07.014379 29145 net.cpp:200] conv2_BN does not need backward computation.
> I0502 15:37:07.014384 29145 net.cpp:200] conv2 does not need backward computation.
> I0502 15:37:07.014389 29145 net.cpp:200] relu1 does not need backward computation.
> I0502 15:37:07.014391 29145 net.cpp:200] conv1_BN does not need backward computation.
> I0502 15:37:07.014395 29145 net.cpp:200] conv1 does not need backward computation.
> I0502 15:37:07.014400 29145 net.cpp:200] data_norm does not need backward computation.
> I0502 15:37:07.014403 29145 net.cpp:200] data does not need backward computation.
> I0502 15:37:07.014407 29145 net.cpp:242] This network produces output final
> I0502 15:37:07.014426 29145 net.cpp:255] Network initialization done.
> I0502 15:37:07.021358 29145 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: HardNet++.caffemodel
> I0502 15:37:07.021405 29145 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
> Initialization and preprocessing time 1.16891098022
> extraction time 0.729129076004
>

**Comment by ducha-aiki** [comment]
@hurricane2018 
It works as is on my machine
