### ISSUE TITLE
Can you explain more about those different HardNet ?

### ISSUE THREAD

**Issue by hurricane2018** [DagnyT/hardnet#12]
![image](https://user-images.githubusercontent.com/36166137/39223831-1618cd6a-4812-11e8-9b39-42979b93f320.png)

There are so many different type of HardNet. Can you explain the with more details ? Thanks !

**Comment by ducha-aiki** [comment]
Hi, 

They are NOT different kinds of HardNet, they are _scripts_ for training HardNet descriptor on the different datasets. Structure of the different datasets are different, they are not just "another folder with images", but patches are stored differently - in mosaic format for Brown, while as "patch column" for HPatches, etc.  I suggest you to read the paper.

Regarding practical use, please see this section https://github.com/DagnyT/hardnet/blob/master/README.md#which-weights-should-i-use
