### ISSUE TITLE
 The Test FPR95 accuracy  is always similar regard of different datasets trained ???

### ISSUE THREAD

**Issue by Sunshine352** [DagnyT/hardnet#18]
while trained on different datasets, including ### **Lib, Not and Yos**, the Test FPR95 accuracy  is ### **almostly the same**. I just run the###  **run_me.sh** using the default parameter.

### **Hardnet trained on  Lib:**
[91mTest set: Accuracy(FPR95): 0.95152000
[91mTest set: Accuracy(FPR95): 0.95264000
Found cached data data/sets/liberty.pt
Generating 5000000 triplets
Found cached data data/sets/notredame.pt
Found cached data data/sets/yosemite.pt

### **Hardnet trained on  Not:**
[91mTest set: Accuracy(FPR95): 0.95128000
[91mTest set: Accuracy(FPR95): 0.95264000
Found cached data data/sets/notredame.pt
Generating 5000000 triplets
Found cached data data/sets/liberty.pt
Found cached data data/sets/yosemite.pt

### **Hardnet trained on  Yos:**
[91mTest set: Accuracy(FPR95): 0.95128000
[91mTest set: Accuracy(FPR95): 0.95152000
Found cached data data/sets/yosemite.pt
Generating 5000000 triplets
Found cached data data/sets/liberty.pt
Found cached data data/sets/notredame.pt

# **## Meanwhile, Hardnet++ met the same problems. May you explain that??? Thank you**

**Comment by ducha-aiki** [comment]
Which version of pytorch do you have? It is very weird that it doesn`t work with default parameters.

**Comment by Sunshine352** [comment]
Suddenly, I again ran the code,  **## results became normal**
