### ISSUE TITLE
where is pytorch_sift ?

### ISSUE THREAD

**Issue by yunyundong** [DagnyT/hardnet#26]
[pytorch_sift ](https://github.com/DagnyT/hardnet/blob/9588b957724c394df6b12c03ba2509df6118a7fe/code/HardNetClassicalHardNegMiningSiftInit.py#L687)

I can not find the file `pytorch_sift ` @DagnyT  @ducha-aiki  @spongezhang

**Comment by DagnyT** [comment]
https://github.com/ducha-aiki/pytorch-sift

**Comment by yunyundong** [comment]
The signature is not the exactly same.
SIFT = SIFTNet(patch_size=patch_size, do_cuda=ON_GPU)
there is no parameter `do_cuda` in the [SIFTNet](https://github.com/ducha-aiki/pytorch-sift)

**Comment by yunyundong** [comment]
Besides, for the script `HardNetClassicalHardNegMiningSiftInit.py`, there are some minor errors:
(1)  [indices = create_indices(labels)](https://github.com/DagnyT/hardnet/blob/9588b957724c394df6b12c03ba2509df6118a7fe/code/HardNetClassicalHardNegMiningSiftInit.py#L200) should be corrected as `indices = create_indices(labels.numpy())`
(2) [for key, value in labels.iteritems():](https://github.com/DagnyT/hardnet/blob/9588b957724c394df6b12c03ba2509df6118a7fe/code/HardNetClassicalHardNegMiningSiftInit.py#L781) should be corrected as `for key, value in labels.items():`

**Comment by DagnyT** [comment]
Yes, true, we didn't update script (HardNetClassicalHardNegMining) with latest pytorch changes and we don't plan to. 
To have the same signature, please, look at older commits for SIFTNet. 
https://github.com/ducha-aiki/pytorch-sift/blob/cff1b3725a9c84cbbb52999653ea3926c2444d69/pytorch_sift.py

**Comment by yunyundong** [comment]
Hi, @DagnyT . I am not very familiar with the functions of github. If you do not give me the link ((https://github.com/ducha-aiki/pytorch-sift/blob/cff1b3725a9c84cbbb52999653ea3926c2444d69/pytorch_sift.py)) of older version of SIFNet,  can I find the the link?

**Comment by yunyundong** [comment]
@DagnyT  Thank you very much for your kind reply. I got it. Thanks again.

**Comment by edgarriba** [comment]
@yunyundong official dfferentiable Sift implementation can be now found in here: https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.SIFTDescriptor
