### ISSUE TITLE
HardNet+ with --augmentation or --fliprot 

### ISSUE THREAD

**Issue by aIR1000** [DagnyT/hardnet#30]
Hello,

I want to know if while training Hardnet+ you used --fliprot only or --augmentation as well? I am assuming it is with fliprot only. If yes, then when is the --augmentation used?

Thanks,

**Comment by aIR1000** [comment]
Also, I faced a little problem when using --resume because of learning decay I suppose it doesn't resume correctly because you aren't saving its state that is why loss jumps to a greater value when resumed. Can you also clarify this?

**Comment by ducha-aiki** [comment]
@aIR1000  both NIPS and current arXiv do not use  --augmentation. It improves results, but all published are without it.

Regarding resume - you are right. We never used it actually, do never debugged :(

**Comment by aIR1000** [comment]
thanks for the quick reply. According to your default setting, learning rate is applied after every iteration (not epoch). right?
And according to your paper (table 2), hardest in batch sampling strategy outperforms the rest in every case but you have highlighted only two columns. Can you explain why?

![capture](https://user-images.githubusercontent.com/44443323/48467493-dc693700-e80a-11e8-8472-be2b995a6338.PNG)

Thanks in advance!

**Comment by aIR1000** [comment]
thanks for the quick reply. According to your default setting, learning rate is applied after every iteration (not epoch). right?

**Comment by DagnyT** [comment]
Yes, right.

**Comment by ducha-aiki** [comment]
@aIR1000 yes, it is linear decay policy 

I don`t remember all references, but bunch of studies shows that it is often optimal way of lr schedule, e.g. here 
https://arxiv.org/abs/1606.02228.pdf

![image](https://user-images.githubusercontent.com/4803565/48475122-6362e300-e7fc-11e8-9949-51b4e1add515.png)

**Comment by ducha-aiki** [comment]
@aIR1000 which HPatches split are you testing on?

**Comment by DagnyT** [comment]
Hi, I've just re-checked for 'full' split (for which we reported)  - checkpoint_liberty_no_aug.pth and got following results: 

   Easy      Hard     Tough     mean
-------  --------  --------  -------
0.69465  0.527253  0.344756  0.52222

Can you please re-check the split.

**Comment by aIR1000** [comment]
hey,
I ran hpatches_extract_HardNet.py to generate descriptors. Then ran hpatches_eval.py with default settings. The default split is "a" I guess. You are evaluating on all these  {a,b,c,full,illum,view}?

**Comment by DagnyT** [comment]
Yes, we evaluate on 'full' set.

**Comment by aIR1000** [comment]
Best, thanks again.
