### ISSUE TITLE
Code of Oxford5k experiments

### ISSUE THREAD

**Issue by appleleaves** [DagnyT/hardnet#31]
I am very interested in your work but do not how to repeat the experiments of Oxford5k and Paris6k.
Would you like to share me the code and give me a hand?

**Comment by ducha-aiki** [comment]
Unfortunately, the answer is the same, is for affnet. We didn't wrote the code, we don't own it and we cannot share it.
You need to implement BoW part yourself.

**Comment by appleleaves** [comment]
Thanks for your answers. I did not realize that you are from the same "we".
