### ISSUE TITLE
Training epochs

### ISSUE THREAD

**Issue by aIR1000** [DagnyT/hardnet#32]
Hello,

I have a small query regarding the training epochs used for different versions. Have you kept 10 epochs for all variants of HardNet? Even for training on full Brown data set?
And what did you use to generate graphs for HPatches evaluation? Did you write the script in Matlab for that?

Thanks in advance!

**Comment by DagnyT** [comment]
Hi!
Yes, it is 10 epochs, the difference for the full Brown set is generating 30M pairs.
For the graphs we've used this script: https://github.com/hpatches/hpatches-benchmark/blob/master/matlab/res_article.m

**Comment by aIR1000** [comment]
thanks :)
