### ISSUE TITLE
Test on yosemite dataset

### ISSUE THREAD

**Issue by Shu-HowTing** [DagnyT/hardnet#38]
Hello,I trained on `liberty`  and  tested on `notredame` successfully. But the following bug appears when i try to `create test_loaders` with `yosemite` dataset :
```
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at ..\aten\src\TH\THGeneral.cpp:188
```

**Comment by DagnyT** [comment]
Hi! Can you please give some more details about your setup. I've just checked with training on liberty and testing on notredame and yosemite, don't see any issues...
