### ISSUE TITLE
Is this loss the same with Batch Hard Loss ?

### ISSUE THREAD

**Issue by XuyangBai** [DagnyT/hardnet#39]
I wonder is this loss the same with Batch Hard Loss proposed in this paper [In Defense of the Triplet Loss for Person Re-Identification](https://arxiv.org/abs/1703.07737). The idea looks quite similar.
<img width="346" alt="屏幕快照 2019-05-12 下午9 22 34" src="https://user-images.githubusercontent.com/15166089/57582826-18503100-74fc-11e9-871f-cf9e950ce66f.png">

**Comment by ducha-aiki** [comment]
It is. Later, we have found that paper (it is the different domain) but get the idea independently and in quite the same time.

**Comment by XuyangBai** [comment]
Sorry I reopen this issue for some further questions. I think the difference between your work and ReID paper is that for your work, one identity (keypoint) only has one instance (descriptor) while for the ReID paper one identity(person) might have several instance(images). So in your batch hard loss, the positive always be the diagonal？ Is my understanding correct?

Thanks a lot .

**Comment by ducha-aiki** [comment]
Yes, it is correct. The reason for it is that the most of classes in Brown dataset (patches) have only 2 positives.
