### ISSUE TITLE
Concerning the "class TripletPhotoTour"

### ISSUE THREAD

**Issue by johnnysclai** [DagnyT/hardnet#4]
I think all the `np.random.randint(0, len(sth) - 1)` should be changed to `np.random.randint(0, len(sth))` instead since the larger integer is excluded according to [NumPy manual](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.random.randint.html).

**Comment by DagnyT** [comment]
Yes, you are right. Thank you! Fixed.
