### ISSUE TITLE
Training Set Label Formatting

### ISSUE THREAD

**Issue by ss32** [DagnyT/hardnet#42]
Could you provide some information on the label formatting for the provided training sets?

What are the two columns of `info.txt`?  Why do some numbers in the first column repeat? What are the columns of `interest.txt` and `m50_XXXX.txt`?  

For context, I am trying to create my own training set for a different type of data and need to train from scratch.

**Comment by DagnyT** [comment]
Hello,

This is Multi-view Stereo Correspondence Dataset structure, you can find more information about it here: http://matthewalunbrown.com/patchdata/patchdata.html

**Comment by ss32** [comment]
Great, thanks!
