### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/sets/liberty.zip' 

### ISSUE THREAD

**Issue by InstantWindy** [DagnyT/hardnet#44]
Hi, When I run the "run_me.sh", it shows "FileNotFoundError: [Errno 2] No such file or directory: 'data/sets/liberty.zip' " error. How to solve it. Thanks

**Comment by DagnyT** [comment]
Hi,
I can't reproduce you error, liberty subset is downloaded directly when start running HardNet.py, in dataset class, it is subclass of: https://github.com/pytorch/vision/blob/master/torchvision/datasets/phototour.py
Maybe some error occurred when you were downloading, I can suggest you to try to re-download it.
