### ISSUE TITLE
local variable 'out_a' referenced before assignment

### ISSUE THREAD

**Issue by Nestart** [DagnyT/hardnet#45]
Thanks for your sharing, when I run hardnet.py by following command ,it raises this error,can you tell me how to solve this problem?

 python ./code/HardNet.py --w1bsroot "$DATASETS/wxbs-descriptors-benchmark/code/" --fliprot=False --n-triplets=500 --experiment-name=liberty_train/ $@ | tee -a "$DATALOGS/log_HardNet_Lib.log"

![Screenshot from 2020-05-26 13-04-32](https://user-images.githubusercontent.com/34918269/82862134-7d34c880-9f51-11ea-9fa7-0b7e466e8460.png)

**Comment by DagnyT** [comment]
Hello,

I can't reproduce this bug, maybe you can share your libraries setup or try to re-install from scratch?
