### ISSUE TITLE
Interrupt when running the HardNet.py sample

### ISSUE THREAD

**Issue by empty16** [DagnyT/hardnet#9]
Hi
When I use the demo code `HardNet.py` with the parameter `--fliprot=False --experiment-name=liberty_train/ --gpu-id=4 `, there always occur an interruption because of the memory usage. I found that the memory usage will increase drastically along with the training epochs, then it will be interrupted by the OS. 
Even I reset the `--n-triplets=500000`, the memory usage will still cause an interruption.
![image](https://user-images.githubusercontent.com/5836072/37237858-f6bdd3ce-2454-11e8-9919-aea96006022e.png)

**Comment by ducha-aiki** [comment]
How much RAM do you have?
You can add 

    import gc

at the beginning of the HardNet.py and add line

    gc.collect()

after calling train function.

**Comment by empty16** [comment]
Thanks for your reply @ducha-aiki .
I run the `HardNet.py` in my docker, and the hardware configurations of my server are as follows:
![image](https://user-images.githubusercontent.com/5836072/37248425-3030b47e-250d-11e8-8f8d-ff3aa0f887e8.png)

After adding the `gc.collect()` after the calling train function as you suggest:

`train(train_loader, model, optimizer1, epoch, logger, triplet_flag)`
`gc.collect()`

There still an interruption at the `epoch=3`.
And I use the `del train_loader`  as well as  `train_loader=None` before the  `gc.collect()`, the interruption is still on.

The memory usage is `4.3%` when `epoch=1`, then it will increase to `7.3%` when `epoch=2`,  finally it will be interrupted by the OS.

The memory usage at  the `epoch=2` is as follows:
![image](https://user-images.githubusercontent.com/5836072/37248422-11d3c1ec-250d-11e8-81fe-c4c88d64c163.png)

What is the minimum memory request by the HardNet?

**Comment by DagnyT** [comment]
Hi! Can you please share your python/pytorch versions and which card do you use?

**Comment by empty16** [comment]
Hi @DagnyT , I run the HardNet on Ubuntu 14.04(x64), Tesla K80(12G), pytorch(0.3.0post4), python(2.7).

It works now after I change the code as follows:
1. Re-write the `create_loaders()` function, the return value now is a `Dataloader(train/test)`, instead of return `train_dataloader,  test_dataloader` at the same time. Because I find the test_dataloader stay unchanged during the training, it may save some data loading time as well as the computing resource.
2. Override the `class DataLoader()` as `class TripletDataLoader()`,  which takes class `TripletPhotoTour` as a member variable. Then I add a class function `resample_dataset_triplets()` 
 in `TripletDataLoader`, which can re-generate TripletPhotoTour triplets with a class function call instead of calling the `create_loaders` after each epoch. 
After the modification, the RAM memory usage is around 4.5%(9G) during the execution.

Hope it may help you.
